all:
  ckeditor:
    basePath:         '/twAdminPlugin/ckeditor/'

  tw_admin:
    web_dir:                      /twAdminPlugin
    image_dir:                    /twAdminPlugin/images/
    
    site:                         My Site
    site_start_year:              2012
    
    include_path:                 true
    include_jquery_no_conflict:   false
    
    default_module:               homepage
    default_category:             index
    default_subcategory:          false
    default_nav:                  navbar
    
    #login:                        false
    #logout:                       true
    
    #login_route:                  '@homepage'
    #logout_route:                 '@homepage'
    
    menu:
      homepage:
        categories: 
          index:
            label: Informations
            url:   '@homepage'
        